add_newline = true

format = """$directory
$character"""

right_format = """$git_branch$git_status$bun$python$nodejs$rust$lua$java$golang$zig$cmd_duration$all"""

[character]
success_symbol = "[ïŒº ](bold #C9B693)"
error_symbol = "[ïŒº ](bold #fb4934)"
vimcmd_symbol = '[ïŒº ](bold fg:#98971a)'
vimcmd_replace_one_symbol = '[ïŒº ](bold fg:#b16286)'
vimcmd_replace_symbol = '[ïŒº ](bold fg:#b16286)'
vimcmd_visual_symbol = '[ïŒº ](bold fg:#d79921)'

[line_break]
disabled = true

[directory]
style = "bold #8ec07c"
truncation_length = 3
truncate_to_repo = true

[git_branch]
style = "bold #d3869b"
symbol = "î‚  "

[git_status]
style = "bold #fabd2f"
conflicted = "=[$count](bold #fb4934)"
ahead = "â‡¡[$count](bold #b8bb26)"
behind = "â‡£[$count](bold #b8bb26)"
diverged = "â‡¡[$ahead_count](bold #b8bb26)â‡£[$behind_count](bold #b8bb26)"
untracked = "?[$count](bold #fe8019)"
stashed = "*[$count](bold #b8bb26)"
modified = "![$count](bold #fe8019)"
staged = "+[$count](bold #b8bb26)"
renamed = "Â»[$count](bold #fe8019)"
deleted = "âœ˜[$count](bold #fb4934)"

[bun]
symbol = "î¯ "
style = "bold #fabd2f"

[docker_context]
symbol = "ïŒˆ "
style = "bg:#665c54"
format = '[[ $symbol( $context) ](fg:#83a598 bg:#665c54)]($style)'

[python]
symbol = "ï¢ "
style = "bold #fabd2f"

[nodejs]
symbol = "îœ˜ "
style = "bold #b8bb26"

[rust]
symbol = "ó±˜— "
style = "bold #fe8019"

[lua]
format = 'via [$symbol($version )]($style)'
version_format = 'v${raw}'
symbol = "î˜  "

[java]
symbol = "îœ¸ "
style = "bold #d3869b"

[golang]
symbol = "î˜§ "
style = "bold #83a598"

[zig]
symbol = "îš© "
style = "bold #fe8019"
format = 'via [$symbol($version)]($style)'

[cmd_duration]
min_time = 500
style = "bold #fabd2f"
format = " [$duration]($style)"

# Backup 
# # Don't print a new line at the start of the prompt
# add_newline = false
# # Pipes â•°â”€ â•­â”€
# # Powerline symbols Â î‚° î‚± î‚² î‚³ î‚´ î‚µ î‚¶ î‚· î‚¸ î‚¹ î‚º î‚» î‚¼ î‚½ î‚¾ î‚¿ îƒ€ îƒ îƒ‚ îƒƒ îƒ„ îƒ… îƒ† îƒ‡ îƒˆ îƒŠ  îƒŒ îƒ îƒ îƒ îƒ îƒ‘ îƒ” îƒ’ 
# # Wedges ğŸ­§ğŸ­’ ğŸ­£ğŸ­§ğŸ­“
# # Random noise ğŸ¬–ğŸ¬¥ğŸ¬”ğŸ¬—
# # Cool stuff ó°œ¥ î©± ï‹ ï€
#
# # format = """
# # $cmd_duration$username$hostname $directory $git_branch
# # $character
# # """
# format = """
# $cmd_duration ó°œ¥ $directory $git_branch $git_commit $git_status
# $character"""
#
# right_format ="""
# $bun$python$nodejs$rust$lua$java$golang$zig$memory_usage"""
#
# # Replace the "â¯" symbol in the prompt with "âœ"
# # [character]                            # The name of the module we are configuring is "character"
# # success_symbol = "[ î©± ï‹]( fg:blue)"
# # error_symbol = "[ ï€ ï‹]( fg:red)"
# #
# # vimcmd_symbol = '[ î©± ï‹]( fg:green)'
# # vimcmd_replace_one_symbol = '[ î©± ï‹]( fg:pink)'
# # vimcmd_replace_symbol = '[ î©± ï‹]( fg:pink)'
# # vimcmd_visual_symbol = '[ î©± ï‹]( fg:orange)'
#
# [character]
# success_symbol = "[ ïŒº ](bold #C9B693)"
# error_symbol = "[ ïŒº ](bold #fb4934)"
# vimcmd_symbol = '[ ïŒº ](bold fg:#98971a)'
# vimcmd_replace_one_symbol = '[ ïŒº ](bold fg:#b16286)'
# vimcmd_replace_symbol = '[ ïŒº ](bold fg:#b16286)'
# vimcmd_visual_symbol = '[ ïŒº ](bold fg:#d79921)'
#
# # Disable the package module, hiding it from the prompt completely
# [package]
# disabled = true
#
# [git_branch]
# style = "bg: cyan"
# symbol = "ó°˜¬"
# truncation_length = 12
# truncation_symbol = ""
# format = "ó°œ¥ [î‚¶]( fg:cyan)[$symbol $branch(:$remote_branch)](fg:black bg:cyan)[î‚´ ]( fg:cyan)"
#
# [git_commit]
# commit_hash_length = 4
# tag_symbol = "ï’¶ "
#
# [git_state]
# format = '[\($state( $progress_current of $progress_total)\)]($style) '
# cherry_pick = "[ğŸ’ PICKING]( red)"
#
# [git_status]
# style = " fg:yellow"
# conflicted = "=[$count]( fg:red)"
# ahead = "â‡¡[$count]( fg:green)"
# behind = "â‡£[$count]( fg:green)"
# diverged = "â‡¡[$ahead_count]( fg:green)â‡£[$behind_count]( fg:green)"
# untracked = "?[$count]( fg:orange)"
# stashed = "*[$count]( fg:green)"
# modified = "![$count]( fg:orange)"
# staged = "+[$count]( fg:green)"
# renamed = "Â»[$count]( fg:orange)"
# deleted = "âœ˜[$count]( fg:red)"
#
# # [hostname]
# # ssh_only = false
# # format =  "[â€¢$hostname](bg:cyan  fg:black)[î‚´]( fg:cyan)"
# # trim_at = ".companyname.com"
# # disabled = false
#
# [line_break]
# disabled = false
#
# [memory_usage]
# threshold = -1
# symbol = " "
# style = " dimmed green"
#
# [time]
# disabled = true
# format = 'ğŸ•™[\[ $time \]]($style) '
# time_format = "%T"
#
# # [username]
# # style_user = " bg:cyan fg:black"
# # style_root = "red "
# # format = "[î‚¶]( fg:cyan)[$user]($style)"
# # disabled = false
# # show_always = true
#
# [directory]
# home_symbol = " ï‘­ "
# read_only = " ï‘– "
# style = "bg:green fg:black"
# truncation_length = 3
# truncation_symbol = " â€¢â€¢/"
# truncate_to_repo = true
# format = '[î‚¶]( fg:green)[ó°‰‹ $path]($style)[î‚´]( fg:green)'
#
# [bun]
# symbol = "î¯ "
# style = " fg:yellow"
#
# [docker_context]
# symbol = "ïŒˆ "
# style = "bg:purple"
# format = '[[ $symbol( $context) ](fg:blue bg:#purple)]($style)'
#
# [python]
# symbol = "ï¢ "
# style = " fg:orange"
#
# [nodejs]
# symbol = "îœ˜ "
# style = " fg:green"
#
# [rust]
# symbol = "ó±˜— "
# style = " fg:red"
#
# [lua]
# format = 'via [$symbol($version )]($style)'
# version_format = 'v${raw}'
# symbol = "î˜  "
#
# [golang]
# symbol = "î˜§ "
# style = " fg:blue"
#
# [zig]
# symbol = "îš© "
# style = " fg:yelllow"
# format = 'via [$symbol($version)]($style)'
#
# [directory.substitutions]
# "Desktop" = " ï’© "
# "Documents" = " ï’¥ "
# "Downloads" = " ï‰ "
# "Music" = " ó°ˆ "
# "Pictures" = " ï "
# "Videos" = " ï”¬ "
# "GitHub" = " ó°Š¤ "
#
# [cmd_duration]
# min_time = 500
# format = '[î‚¶]( fg:yellow)[ó°ª¢ $duration]( bg:yellow fg:black)[î‚´]( fg:yellow)'
